version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orri_development
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: 
      - sh
      - -c
      - |
        rm -f tmp/pids/server.pid
        bundle install
        bin/rails s -p 3000 -b '0.0.0.0'
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    volumes:
      - .:/rails
      - bundle_path:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db  
    stdin_open: true
    tty: true
    user: user

volumes:
  db_data:
  bundle_path:
